#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          cgit
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: spawn-fcgi/fcgiwrap wrapper for cgit
### END INIT INFO

DESC="cgit"
SCRIPT=/usr/lib/cgit/cgit.cgi
PIDFILE=/var/run/cgit.pid
SOCKET=/var/run/cgit.sock

FCGIWRAP=/usr/sbin/fcgiwrap
DAEMON=/usr/bin/spawn-fcgi
DAEMON_ARGS="-s ${SOCKET} -u git -U www-data -P ${PIDFILE}"
DAEMON_ARGS="${DAEMON_ARGS} -- ${FCGIWRAP} /usr/lib/cgit/cgit.cgi"

do_stop_cmd() {
  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 \
      --pidfile ${PIDFILE} --exec ${FCGIWRAP}
  rm -f ${PIDFILE} ${SOCKET}
}
